#! /bin/bash

sudo yum groupinstall -y "Development Tools"
sudo yum install -y rpm-build redhat-rpm-config asciidoc hmaccalc perl perl-ExtUtils-Embed pesign xmlto
sudo yum install -y audit-libs-devel binutils-devel elfutils-devel elfutils-libelf-devel java-devel
sudo yum install -y ncurses-devel newt-devel numactl-devel pciutils-devel python-devel python-docutils zlib-devel kernel-devel
sudo yum install -y sh-utils tar xz patch m4 make module-init-tools net-tools openssl findutils flex gawk gcc gettext gzip hostname binutils bc bison diffutils 


KERNEL_VERSION=$(uname -r|sed -e "s/\.$(uname -m)//g")
KERNEL_SRC="kernel-${KERNEL_VERSION}.src.rpm"
CENT_VERSION=$(cat /etc/redhat-release|awk '{print $3}')
CENT_SRC="http://vault.centos.org/${CENT_VERSION}/updates/Source/SPackages/${KERNEL_SRC}"
echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros
mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
cd ~/rpmbuild/SPECS
rpmbuild -bp --target=$(uname -m) kernel.spec
