#!/bin/bash

sudo apt-get update
sudo apt-get install linux-headers-$(uname -r)
sudo apt-get install bc bison build-essential chrpath cmake diffstat flex gawk gcc gcc-multilib git kmod libelf-dev libssl-dev libncurses5-dev libsdl1.2-dev lzop make socat texinfo unar unzip wget xterm 

