#!/bin/bash

sudo apt update
sudo apt upgrade
sudo apt install linux-headers-$(uname -r)
sudo apt install bc bison build-essential chrpath cmake diffstat flex gawk gcc gcc-multilib git kmod libelf-dev libssl-dev libncurses5-dev libsdl1.2-dev lzop make socat texinfo unar unzip wget xterm 

